# Generated by Django 2.0.4 on 2019-07-21 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Measurements',
            fields=[
                ('timestamp', models.DateTimeField(max_length=24, primary_key=True, serialize=False)),
                ('tempareture', models.FloatField()),
                ('dewPoint', models.FloatField()),
                ('precipitation', models.FloatField()),
            ],
        ),
    ]
