# Generated by Django 2.0.4 on 2019-07-21 16:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='measurements',
            old_name='tempareture',
            new_name='temperature',
        ),
    ]
